### ISSUE TITLE
Headless

### ISSUE THREAD

**Issue by DekaSKy** [dobizz/awbot#4]
After uncommit headless mode

	Switching to new window.
Traceback (most recent call last):
  File "C:\Users\Devos\Desktop\awbot-main\awbot.py", line 276, in <module>
    main()
  File "C:\Users\Devos\Desktop\awbot-main\awbot.py", line 240, in main
    btn = WebDriverWait(driver, 60).until(ec.visibility_of_element_located((By.XPATH, "//*[contains(text(), 'Approve')]")))
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
Backtrace:
	Ordinal0 [0x0038FDC3+2555331]
	Ordinal0 [0x003277F1+2127857]
	Ordinal0 [0x00222E08+1060360]
	Ordinal0 [0x0024E49E+1238174]
	Ordinal0 [0x0024E69B+1238683]
	Ordinal0 [0x00279252+1413714]
	Ordinal0 [0x00267B54+1342292]
	Ordinal0 [0x002775FA+1406458]
	Ordinal0 [0x00267976+1341814]
	Ordinal0 [0x002436B6+1193654]
	Ordinal0 [0x00244546+1197382]
	GetHandleVerifier [0x00529622+1619522]
	GetHandleVerifier [0x005D882C+2336844]
	GetHandleVerifier [0x004223E1+541697]
	GetHandleVerifier [0x00421443+537699]
	Ordinal0 [0x0032D18E+2150798]
	Ordinal0 [0x00331518+2168088]
	Ordinal0 [0x00331660+2168416]
	Ordinal0 [0x0033B330+2208560]
	BaseThreadInitThunk [0x75D06739+25]
	RtlGetFullPathName_UEx [0x76F88AFF+1215]
	RtlGetFullPathName_UEx [0x76F88ACD+1165]

**Comment by dobizz** [comment]
This happens usually when the game is congested and it takes a long time for anything to load, even if you are playing manually. You can increase the timeout value in WebDriverWait(driver, 60), but I think it is better to just shut down the bot if the game itself is unplayable.

**Comment by DekaSKy** [comment]
> This happens usually when the game is congested and it takes a long time for anything to load, even if you are playing manually. You can increase the timeout value in WebDriverWait(driver, 60), but I think it is better to just shut down the bot if the game itself is unplayable.

But it always comes up when open popup window approve clame
